version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"

sphinx:
   configuration: doc/source/conf.py

formats:
   - pdf

python:
   install:
   - requirements: requirements-dev.txt
   - method: pip
     path: .
