[tool.pyright]
exclude = [
    "**/__pycache__",
    "doc/**",
    "tasks.py",
    "static_frame/test/unit",
    "static_frame/test/integration",
    "static_frame/test/property",
    "static_frame/profile",

    "static_frame/core/type_blocks.py",
    "static_frame/core/index_hierarchy.py",
    "static_frame/core/frame.py",
    "static_frame/core/container_util.py",
    "static_frame/core/bus.py",
    "static_frame/core/yarn.py",
    "static_frame/core/quilt.py",
    "static_frame/core/pivot.py",
    "static_frame/core/batch.py",
    "static_frame/core/protocol_dfi.py",
    "static_frame/core/display*",
    "static_frame/core/node*",
    "static_frame/core/store*",
    "static_frame/core/interface.py",
]

typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
reportUnboundVariable = "none"
reportInvalidTypeVarUse = false

pythonVersion = "3.11"
pythonPlatform = "Linux"



