[tool.isort]
line_length = 200
force_single_line = true


[tool.pyright]
exclude = [
    "**/__pycache__",
    "doc/**",
    "tasks.py",
    "static_frame/test/unit",
    "static_frame/test/integration",
    "static_frame/test/property",
    "static_frame/profile",

    "static_frame/core/frame.py",
    "static_frame/core/container_util.py",
    "static_frame/core/bus.py",
    "static_frame/core/yarn.py",
    "static_frame/core/quilt.py",
    "static_frame/core/pivot.py",
    "static_frame/core/batch.py",
    "static_frame/core/protocol_dfi.py",
    "static_frame/core/display*",
    "static_frame/core/node*",
    "static_frame/core/store*",
    "static_frame/core/interface.py",
]

typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
reportUnboundVariable = "none"
reportInvalidTypeVarUse = false
pythonVersion = "3.11"
pythonPlatform = "Linux"


[tool.mypy]
files = "static_frame/**/*.py"
show_error_codes = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
warn_return_any = true
warn_unused_configs = true
disable_error_code = "misc"

[[tool.mypy.overrides]]
module = [
    "IPython",
    "openpyxl",
    "pandas",
    "pyarrow",
    "pytest",
    "setuptools",
    "sphinx.*",
    "sphinx_rtd_theme",
    "scipy.*",
    "tables",
    "xarray",
    "xlsxwriter.*",
    "arraymap",
    "frame_fixtures",
    ]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "doc.*",
    "static_frame.profile.*",
    "static_frame.core.display_visidata",
    "static_frame.test.property.*",
    "static_frame.test.unit.*",
    "static_frame.test.integration.*",
    ]
ignore_errors = true

