name: CI

on:
  push:
    branches:
    - master
  pull_request:

env:
  CFLAGS: -Wno-error=implicit-function-declaration

jobs:
  #-----------------------------------------------------------------------------
  test_3_08:
    name: Test / ${{ matrix.os.name }} / Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - {name: 'ubuntu-20.04', pip_cache: '~/.cache/pip'}
          - {name: 'windows-2019', pip_cache: '~\AppData\Local\pip\Cache'}
          - {name: 'macos-11', pip_cache: '~/Library/Caches/pip'}
        python-version: ['3.8']
    runs-on: ${{ matrix.os.name }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ${{ matrix.os.pip_cache }}
        key: test-pip-${{ matrix.os.name }}-${{ matrix.python-version }}-${{ hashFiles('requirements-test-3_08.txt', '.github/workflows/ci.yml') }}
        restore-keys: test-pip-${{ matrix.os.name }}-${{ matrix.python-version }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test-3_08.txt

    - name: Invoke Test
      run: inv test --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: 6de39346-7381-441d-80d3-a6c0c051be2d
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true

  #-----------------------------------------------------------------------------
  test_3_9_to_3_11:
    name: Test / ${{ matrix.os.name }} / Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - {name: 'ubuntu-22.04', pip_cache: '~/.cache/pip'}
          - {name: 'windows-2022', pip_cache: '~\AppData\Local\pip\Cache'}
          - {name: 'macos-13', pip_cache: '~/Library/Caches/pip'}
        python-version: ['3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os.name }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ${{ matrix.os.pip_cache }}
        key: test-pip-${{ matrix.os.name }}-${{ matrix.python-version }}-${{ hashFiles('requirements-test-3_11.txt', '.github/workflows/ci.yml') }}
        restore-keys: test-pip-${{ matrix.os.name }}-${{ matrix.python-version }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test-3_11.txt

    - name: Invoke Test
      run: inv test --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: 6de39346-7381-441d-80d3-a6c0c051be2d
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true

  #-----------------------------------------------------------------------------
  quality_3_11:
    name: Quality / ${{ matrix.os }} / Python ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04']
        python-version: ['3.11']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: quality-pip-${{ hashFiles('requirements-dev-3_11.txt', '.github/workflows/ci.yml') }}
        restore-keys: quality-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev-3_11.txt

    - name: Invoke Quality
      run: inv quality

  #-----------------------------------------------------------------------------
  test_ex_3_11:
    name: Test Examples / ${{ matrix.os }} / Python ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04']
        python-version: ['3.11']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: quality-pip-${{ hashFiles('requirements-test-3_11.txt', '.github/workflows/ci.yml') }}
        restore-keys: quality-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test-3_11.txt

    - name: Test Example Generation
      run: inv testex --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: 6de39346-7381-441d-80d3-a6c0c051be2d
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true