name: TestBackward

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7

      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: test-backward-pip-${{ hashFiles('requirements-test-backward.txt', '.github/workflows/test_backward.yml') }}
        restore-keys: test-backward-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel==0.35.1
        pip install numpy==1.17.4
        pip install Cython==0.29.13
        pip install setuptools==41.2.0
        pip install -r requirements-test-backward.txt

    - name: Invoke Test
      run: inv test --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage.xml
        fail_ci_if_error: false
        verbose: true