name: Test Example Generation

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test_ex_3_11:
    name: Test Examples / ${{ matrix.os }} / Python ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04']
        python-version: ['3.11']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: quality-pip-${{ hashFiles('requirements-test-3_11.txt', '.github/workflows/quality.yml') }}
        restore-keys: quality-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Test Example Generation
      run: inv testex --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: 6de39346-7381-441d-80d3-a6c0c051be2d
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true